### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by petrosh** [petrosh/snippetrosh#16]
| [SASS](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-268495268) |
|:---:|

- [Selectors](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-267071616)
- [Clearing floats](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-268078068)
- [Fonts](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-1417707731)
- [`<details>` CSS polyfill](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-229880848)
- [Snippets](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-268495747)
- [Themes](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-271603580)
- [Mobile](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-285694927)
- [Flexbox](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-288693635)
- [Safari fixes](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-344604591)
- [Counters](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-359816875)
- [Dark Theme](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-591500146)
- [Tab focus](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-615257013)
- [Loading status, wait](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-997452703)
- [SVG](https://github.com/petrosh/snippetrosh/issues/16#issuecomment-1398668542)
- Scrollbar colors: `:root{scrollbar-color: thumb track;}`

## Links

- [Devtools tricks](https://css-tricks.com/using-devtools-tweak-designs-browser/)
- [HTML color names](http://htmlcolorcodes.com/color-names/)
- [Codepen stripes](http://codepen.io/Petrosh/pen/gmmBax)

**To do**

- [ ] https://css-tricks.com/adding-stroke-to-web-text/

**Comment by petrosh** [comment]
## `<details>` polyfill
- [CodePen](http://codepen.io/Petrosh/pen/bpZavx)

``` html
<div class="details">
  <p class="summary">Ennamo</p>
  <p>first</p>
  <ul>
    <li>no</li>
    <li>si</li>
  </ul>
  <div class="details">
    <p class="summary">Chiusi</p>
    <p>Second</p>
    <ul>
      <li>1</li>
      <li>2</li>
    </ul>
    <div class="details">
      <p class="summary">Mizzeca</p>
      <p>Terza</p>
      <ul>
        <li>storia</li>
        <li>nera</li>
      </ul>
    </div>
  </div>
</div>
<div class="details">
  <p class="summary">Mizzeca</p>
  <p>Terza</p>
  <ul>
    <li>storia</li>
    <li>nera</li>
  </ul>
</div>
```

``` css
@charset "UTF-8";
.details {}
.details > .summary {
  cursor: pointer;
  user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -o-user-select: none;
}
.details > .summary:before {
  display: inline-block;
  width: 1.3em;
  font-size: small;
  content: "►";
}
.details > *:not(.summary) {
  display: none;
}
.details[open] > .summary:before {
  content: "▼";
}
.details[open] > * {
  display: block;
}
```

``` js
var details, target, summary;
details = document.querySelectorAll('.details');
for(var i = 0; i < details.length; i++){
  detail = details[i];
  summary = detail.querySelector('.summary');
  summary.addEventListener('click', function (e) {
    e.preventDefault();
    target = e.target.parentNode;
    if (target.getAttribute('close')) {
      target.removeAttribute('close');
      target.setAttribute('open', 'open');
    } else if(target.getAttribute('open')) {
      target.removeAttribute('open');
      target.setAttribute('close', 'close');
    } else {
      target.setAttribute('open', 'open');
    }
  });
}
```

**Comment by petrosh** [comment]
# Selectors

## `attr()` for `content`

Used to retrieve the value of an attribute of the selected element and use it in the style sheet.

```html
<p data-foo="hello">world</p>
```

```sass
p::before
  content: attr(data-foo) " "
```

Results in "hello world"

## Text selection

```css
::selection,
::-moz-selection {
  background: #ffb7b7;
}
```

## Attributes

``` css
a[href$="ABC" i] {
/*
  = its exactly equal
  != its not equal
  ^= it starts with
  $= it ends with
  *= it contains (substring, check below)
  ~= whitespace separated selector (you won't get burned by
     something like "expand" matching "expander" when you didn't want to.)
  i Adding an `i` (or `I`) before the closing bracket
  causes the value to be compared case-insensitively
*/
}

/* Multiple values */
[data-type~="accordion"][data-type~="expand"] {
  /* both present */
}
```

## Sibling combinators

**Negation pseudo-class**
Select an element that is not represented by its argument
```css
a:not(:last-child) /* Style all but the last */
body:not(.index-md) > header > h1 /* Style header link except in home page */
```

**Adiacent-sibling combinator**  
Select the element that immediately follows the former, and both are children of the same parent.
```css
img + span.caption
```

**General-sibling combinator**  
Select the second element only if it is preceded by the first (not necessarily immediately), and both share a common parent.
```css
p ~ span
```

**Child combinator**

Select element child of the former: second selector must be the **immediate children** of the first selector.

```css
body > p
```

**Last child of a parent**

```css
.parent > :last-child
/* means .parent > *:last-child */
```

## Pseudo classes

- [pseudo-classes <sup>Medium</sup>](https://medium.freecodecamp.com/explained-css-pseudo-classes-cef3c3177361#.v5m3216tk)

**Type**

```css
a:only-of-type
a:first-of-type
a:last-of-type /* the last element of its type among a group of sibling elements. */
a:nth-of-type(n) /* accept numbers, formula, even/odd */
a:nth-last-of-type(n)
```

**Child**

```css
a:only-child /* Select the element should be the only child of its parent */
a:first-child /* Select the element should be the first child of its parent */
a:last-child
a:nth-child(n)  /* accept numbers, formula, even/odd */
a:nth-last-child(n)
```

**Empty**

The `:empty` CSS pseudo-class represents any element that **has no children**. Children can be either element nodes or text (including whitespace).

```css
/* Selects any <div> that contains no content */
div:empty {
  background: lime;
}
```

**Recipes**

```css
a:nth-child(odd) /* Select only odd (1, 3, 5...) */
a:nth-child(-n+5) /* Select only the first five */
a:nth-child(n+6) /* Select all but the first 5 */
a:nth-child(4n-7) /* Select every fourth starting at the first */
```

## Anchor links

``` css
h2:target, h3:target, li:target {
    background-color: #fffacd;
}
```

https://github.github.io/fetch/#credentials

## First of the First

```css
#markdown-toc > li > a {
    background:red;
}
```

```html
<ul id="markdown-toc">
    <li>
        <a href="#">Link</a>
    </li>
</ul>
```

**Comment by petrosh** [comment]
## Clearing floats

**Adding div** <sup>[css tricks](https://css-tricks.com/the-how-and-why-of-clearing-floats/)</sup>
Add after your last floated object.

```html
<div style="clear: both;"></div>
```

**Overflow** <sup>[css tricks](https://css-tricks.com/the-how-and-why-of-clearing-floats/#comment-15)</sup>

```css
#main_container {overflow: auto}
```

**Line break** <sup>[css tricks](https://css-tricks.com/the-how-and-why-of-clearing-floats/#comment-9)</sup>

```css
.brclear {
    clear:both;
    height:0;
    margin:0;
    font-size: 1px;
    line-height: 0;
}
```

**Pseudo selector** <sup>[css tricks](https://css-tricks.com/all-about-floats/#article-header-id-4)</sup>

```css
.clearfix:after { 
   content: "."; 
   visibility: hidden; 
   display: block; 
   height: 0; 
   clear: both;
}
```

**Comment by petrosh** [comment]
# Sass

**Update from terminal**

```sh
sudo gem update sass
```

**Define null and check**

```sass
$check: null
.nothing
  @if $check
    // not executed
```

**Conditional**

```sass
body > div.flex
  @if $sidebar-side == left
    flex-direction: row
  @if $sidebar-side == right
    flex-direction: row-reverse
```

**Extend classes**

```sass
// single
.single
  @extend: .container
// multiple
.multiple
  @extend .zio, .zia, .lella
// from list
$classes: small px-2 py-1 mb-2
.from-list
  @if $classes
    @each $class in $classes
      @extend .#{$class}
```

```sass
// mixin
@mixin estendi($class_list)
  @each $class in $class_list
    @extend .#{$class}
// example
p
  @include estendi(mt-5 mb-3 fw-3)
```

**Loop array and apply classes**

- [Even Better @each loops with Sass 3.3](http://www.alwaystwisted.com/articles/2014-03-06-even-better-each-loops-with-sass-33)
- Demo: [domtools](//github.com/petrosh/domtools)

``` sass
$brand-color:   #4078c0
$lightred:      #c04040
$forest:        #40bf46
$melma:         #009688
$cave:          #a45e0a

$page-colours: (lightred, $lightred), (forest, $forest), (melma, $melma), (cave, $cave)

@each $brand, $color in $page-colours
    body.#{$brand}
        main a
            color: $color
        header
            background-color: $color
```

**Compiled**

``` css
body.lightred main a {
  color: #c04040; }
body.lightred header {
  background-color: #c04040; }

body.forest main a {
  color: #40bf46; }
body.forest header {
  background-color: #40bf46; }

body.melma main a {
  color: #009688; }
body.melma header {
  background-color: #009688; }

body.cave main a {
  color: #a45e0a; }
body.cave header {
  background-color: #a45e0a; }
```

## Breakpoints

``` sass
@mixin breakpoint($class)
  @if $class == xs
    @media (max-width: 767px) @content

  @else if $class == sm
    @media (min-width: 768px) @content

  @else if $class == md
    @media (min-width: 992px) @content

  @else if $class == lg
    @media (min-width: 1200px) @content

  @else
    @warn "Breakpoint mixin supports: xs, sm, md, lg"

# USAGE
aside.primary
  @include breakpoint(md)
    float: right
    width: 350px
```

### Lines background

```sass
// BACKGROUND LINES
// Vertical
@mixin background-lines-v($width, $lines, $background-color, $line-color)
  background: linear-gradient(90deg, #{$background-color} calc(100% - #{$width}), #{$line-color} 0)
  background-size: calc((100% - #{$lines}*#{$width})/(#{$lines} + 1) + #{$width}) 100%
// Horizontal
@mixin background-lines-h($width, $lines, $background-color, $line-color)
  background: linear-gradient(0deg, #{$background-color} calc(100% - #{$width}), #{$line-color} 0)
  background-size: 100% calc((100% - #{$lines}*#{$width})/(#{$lines} + 1) + #{$width})
```

In `css`

``` css
/* add vendor prefix */
textarea{
  background-image: linear-gradient(rgba(150,143,123,.2)1px,rgba(0, 0, 0, 0) 0);
  background-size: auto 24px;
  line-height: 24px;
  background-attachment: scroll;
  background-origin: content-box;
}
```

**List**

```sass
$grid-breakpoints:  (xs: 0,  sm: 576px,  md: 768px,  lg: 992px,  xl: 1100px)
```

## Headings

```sass
// HEADINGS

// Mixin
// @include headings(1,6,':first-child','main > ')
//   content
// main > h1:first-child, main > .h1:first-child
//   content
@mixin headings($from: 1, $to: 6, $condition: '', $prescope: '')
  @for $i from $from through $to
    #{$prescope}h#{$i}#{$condition}, #{$prescope}.h#{$i}#{$condition}
      @content

@mixin estendi($class_list)
  @each $class in $class_list
    @extend .#{$class}
// Set font-weight and font-family for Headings
@include headings()
  @extend .fw-3
  font-family: $font-family-headings

main
  // Set margin top and bottom for Headings inside <main>
  @include headings()
    @include estendi(mt-5 mb-3)
  // Reset margin-top for top-of-page headings
  .col
    @include headings(1,6,':first-child')
      @extend .mt-0
```

**Comment by petrosh** [comment]
## Snippets

**Full page background**

```css
html { 
  background: url(images/bg.jpg) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
```

**Spaces in element content `\00a0`**

``` css
nav ul li::after {
  content: "\00a0\00a0•";
}
```

**Use attribute value**

``` html
<style>
a:after {content: " (" attr(href) ")";}
</style>
<a href="https://github.com/petrosh">link</a>
```

[link (https://github.com/petrosh)](https://github.com/petrosh)

**Change CSS theme**

``` html
<link rel="stylesheet" href="css/theme/black.css" id="theme">
<a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;">Black (default)</a>
```

**Weight name mapping** <sup>[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight)</sup>
Common weight name mapping

```
100 Thin (Hairline)
200 Extra Light (Ultra Light)
300 Light
400 Normal
500 Medium
600 Semi Bold (Demi Bold)
700 Bold
800 Extra Bold (Ultra Bold)
900 Black (Heavy)
```

**Comment by petrosh** [comment]
## Themes

- [GitHub dark](https://bounty.github.com/targets/gist.html)
- [Latex font](https://github.com/dreampulse/computer-modern-web-font)
- [Mastering HTTP Caching](https://blog.fortrabbit.com/mastering-http-caching)
- [Funnel by Mixpanel](https://mixpanel.com/funnels/)
- [Duncan Trussell](http://www.duncantrussell.com/)
- [GitHub footer](https://github.com/logos)

**normalize.css**

- Repository: https://github.com/necolas/normalize.css
- Static v4.2.0: https://petrosh.github.io/assets/css/normalize.css 

**octicons.css**

- Download from https://octicons.github.com/ and include `build/font` folder
- Static v4.2.0: https://petrosh.github.io/assets/css/octicons/octicons.css
- [Delivering octicons with SVG](https://github.com/blog/2112-delivering-octicons-with-svg) – February 22, 2016

**external.css**

- Static: https://petrosh.github.io/assets/css/external.css

**Comment by petrosh** [comment]
# Mobile

## Responsive font size

- [Design a responsive site with em-based sizing](http://www.creativebloq.com/how-to/design-a-responsive-site-with-em-based-sizing)
- Demo: https://gattiecani.github.io/renderizer/html/responsive/

```css
html {
  font-size: calc(0.6em + 1vw);
}
/* Inverse for mobile */
html {
  font-size: calc(1.5em - 0.2vw);
}
```

## Breakpoints mixin SCSS

```scss
@mixin for-size($range) {
  $phone-upper-boundary: 600px;
  $tablet-portrait-upper-boundary: 900px;
  $tablet-landscape-upper-boundary: 1200px;
  $desktop-upper-boundary: 1800px;

  @if $range == phone-only {
    @media (max-width: #{$phone-upper-boundary - 1}) { @content; }
  } @else if $range == tablet-portrait-up {
    @media (min-width: $phone-upper-boundary) { @content; }
  } @else if $range == tablet-portait-only {
    @media (min-width: $phone-upper-boundary) and (max-width: #{$tablet-portrait-upper-boundary - 1}) { @content; }
  } @else if $range == tablet-landscape-up {
    @media (min-width: $tablet-landscape-upper-boundary) { @content; }
  } @else if $range == tablet-landscape-only {
    @media (min-width: $tablet-portrait-upper-boundary) and (max-width: $tablet-landscape-upper-boundary - 1px) { @content; }
  } @else if $range == desktop-up {
    @media (min-width: $tablet-landscape-upper-boundary) { @content; }
  } @else if $range == desktop-only {
    @media (min-width: $tablet-landscape-upper-boundary) and (max-width: $desktop-upper-boundary - 1px) { @content; }
  } @else if $range == big-desktop-up {
    @media (min-width: $desktop-upper-boundary) { @content; }
  }
}

// usage
.my-box {
  padding: 10px;
  
  @include for-size(desktop-up) {
    padding: 20px;
  }
}
```

**Compiled**

```css
.my-box {
  padding: 10px;
}
@media (min-width: 1200px) {
  .my-box {
    padding: 20px;
  }
}
```

## Micca

- [Micca google check](https://search.google.com/search-console/mobile-friendly?id=xLw45As4iFXFt4wKbECU8g)

```css
/*
* 2017
* Mobile friendly
*/

/* For Mobile */
@media screen and (max-width: 540px) {
/*font size*/
	body,
	#topmenu ul li,
	.corpo-serata .testo,
	.corpo-serata h2,
	.corpo-serata h3 { font-size: 1em !important; }

/*SCREEN*/
	#content,
	#container {
		width: auto !important;
	}

/*HIDE*/
	#topmenu,
	#left,
	#right {
		display: none !important;
	}

/*hide sidebars*/
  #outer{ border: none; }

/*maximize image*/
	.corpo-serata > img:first-child,
	p a img,
	#banner a img,
	img[src*='img/linea_footer.gif'] {
		width: 96% !important;
		height: auto;
	}

	/*center lang date*/
	#lang span.daily {
		float: none;
		margin: 0;
	}
	#lang { text-align: center; }
}
```

**Comment by petrosh** [comment]
## Flexbox

### Links

- [Flexboxes, the CSS Unicorn := newbie corner](https://medium.com/@melvinodsa/flexboxes-the-css-unicorn-newbie-corner-8825ed2793a5#.lxj8b0bfs)
- [A Complete Guide to Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

### Usage

#### `display`

```css
.my-div-container{
  display: -webkit-box;  /* OLD - iOS 6-, Safari 3.1-6, BB7 */
  display: -ms-flexbox;  /* TWEENER - IE 10 */
  display: -webkit-flex; /* NEW - Safari 6.1+. iOS 7.1+, BB10 */
  display: flex;
}
```

#### `justify-content`

Horizontal

```css
justify-content: flex-start | flex-end | center | space-between | space-around;
```

![1-qlgsaiuxkqh9hwtx-nhb9g](https://cloud.githubusercontent.com/assets/4997583/24246189/77004fac-0fc6-11e7-8081-bc1065ffbaab.png)

#### `align-items`

Vertical

```css
align-items: flex-start | flex-end | center | stretch | baseline;
```

![1-vhsmnjbbx9v7e2garq1pyw](https://cloud.githubusercontent.com/assets/4997583/24246381/5c98c620-0fc7-11e7-9d3f-905b4fd351df.png)

#### `align-self`

Vertical, override `align.items` for an item

```css
align-self: flex-start | flex-end | center | stretch | baseline;
```

#### `flex-direction`

Order of items

```css
flex-direction: row | row-reverse | column | column-reverse;
```

**Comment by petrosh** [comment]
# Safari fixes

Font rendering https://petrosh.github.io/hal9000-screensaver/

```sass
body
  -webkit-font-smoothing: subpixel-antialiased
```

**Comment by petrosh** [comment]
# Counters

```css
body {
  counter-reset: section;                     /* Set a counter named 'section', and it`s initial value is 0. */
}

h3::before {
  counter-increment: section;                 /* Increment the value of section counter by 1 */
  content: counter(section);                  /* Display the value of section counter */
}
```

**Comment by trasparente** [comment]
# Dark theme

```css
html {
  filter: invert(1) hue-rotate(180deg) brightness(0.9);
}
```

## `prefers-color-scheme` css

```css
@media not all and (prefers-color-scheme) {
  /* Not supported
  Note: In Level 3, the not keyword can't be used to negate
  an individual media feature expression,
  only an entire media query. */
}

@media (prefers-color-scheme) {
  /* Supported */
}

@media (prefers-color-scheme: light) {
  /* light color scheme */
}

@media (prefers-color-scheme: dark) {
  /* dark color scheme */
}

@media (prefers-color-scheme: no-preference) {
  /* no preference */
}
```

**Helper class `.prefers-color-scheme`**

```sass
//
// prefers-color-scheme
// --------------------------------------
@media not all and (prefers-color-scheme)
  .prefers-color-scheme::after
    content: "not-supported"

@media (prefers-color-scheme)
  .prefers-color-scheme::after
    content: "supported"

@media (prefers-color-scheme: light)
  .prefers-color-scheme::after
    content: "light"

@media (prefers-color-scheme: dark)
  .prefers-color-scheme::after
    content: "dark"

@media (prefers-color-scheme: no-preference)
  .prefers-color-scheme::after
    content: "no-preference"
```

## [prefers-color-scheme] js

```js
const isDarkMode = window.matchMedia("(prefers-color-scheme: dark)").matches
const isLightMode = window.matchMedia("(prefers-color-scheme: light)").matches
const isNotSpecified = window.matchMedia("(prefers-color-scheme: no-preference)").matches
const hasNoSupport = !isDarkMode && !isLightMode && !isNotSpecified;
```

## Toggle syntax highlight stylesheet

```coffee
# prefers-color-scheme
# --------------------------------------

# Toggle syntax stylesheet
matchMedia = (e) ->
  $.grep(document.styleSheets, (css) => css.title == "dark #{e}")[0].disabled = false
  $.grep(document.styleSheets, (css) => css.title == "dark #{!e}")[0].disabled = true

# Initial dispatch
matchMedia window.matchMedia("(prefers-color-scheme: dark)").matches

# Event listener
window.matchMedia('(prefers-color-scheme: dark)').addListener (e) -> matchMedia(e.matches)
```

```html
<!-- Syntax light -->
<link rel="stylesheet" title="dark false" href="{{ site.css.syntax | default: 'github.css' | prepend: '/assets/css/syntax/' }}">

<!-- Syntax dark -->
<link rel="stylesheet" title="dark true" href="{{ site.css.syntax | default: 'molokai.css' | prepend: '/assets/css/syntax/' }}">
```

## Firefox

- `ui.systemUsesDarkTheme` = light `0`, dark `1`, no preference `2`
- `devtools.inspector.color-scheme-simulation.enabled: true`

## Disabled links

Simulate disabled link:
```sass
a[disabled]
  text-decoration: none
  pointer-events: none
  cursor: default
  color: unset
```
